<?php
/**
 * Created by PhpStorm.
 * User: ypoon
 * Date: 19/7/2018
 * Time: 5:35 PM
 */

namespace App\FormType\Component;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompositeCollectionType extends AbstractType {
	private $transformer;
	public function __construct(CompositeCollectionTransformer $transformer) {
		$this->transformer = $transformer;
	}

	public function buildForm(FormBuilderInterface $builder, array $options) {
		parent::buildForm($builder, $options);
		$this->transformer->setAllowDuplicate($options["allow_duplicate"]);
        $builder->addModelTransformer($this->transformer);
	}

	public function getParent() {
		return CollectionType::class;
	}

	public function getBlockPrefix() {
		return "composite_collection";
	}

	public function configureOptions(OptionsResolver $resolver) {
		parent::configureOptions($resolver); // TODO: Change the autogenerated stub
		$resolver->setDefaults([
			"allow_add" => true,
			"allow_delete" => true,
			"prototype" => true,
            "allow_duplicate" => false
		]);
	}


}